# Build Stage
FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc pkg-config bison flex

COPY . /dtc
WORKDIR /dtc
RUN make
RUN make install DESTDIR=/install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
